# General Data
name: iConomy
main: com.iCo6.iConomy
version: 6.0.10b

# Generator Data
generators: [bukget]
categories: [ECON]
description: Simple, easy, and intuitive economy for minecraft.
maintainer: Nijikokun
authors: [Nijikokun, SpaceManiac]
website: http://ico.nexua.org
thread: http://bit.ly/iConomy
location: "http://mirror.nexua.org/iConomy/Latest Build/iConomy.jar"
conflicts: []
required: []
optional: [Permissions]
engine:
    craftbukkit:
        min: 0
        max: 1100
    glowstone:
        min: 1
        max: 100
